/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Module = {
  _id: string;
  _type: "module";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  short_title?: string;
  slug?: Slug;
  thumbnail?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: Array<{
    children?: Array<
      | {
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }
      | {
          asset?: SanityFileAssetReference;
          media?: unknown;
          _type: "video";
          _key: string;
        }
    >;
    style?: "normal" | "h3" | "h4" | "h5" | "h6";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  type?: "studio" | "personal" | "internship" | "client" | "other";
  other_type?: string;
  category?:
    | "app"
    | "ai-tool"
    | "digital-tool"
    | "graphic-design"
    | "system-interface"
    | "website"
    | "web-application";
  collaborator?: boolean;
  partner?: {
    label?: string;
    value?: string;
    link?: string;
  };
  location?: {
    name?: string;
    website?: string;
  };
  time?: {
    duration?: string;
    year?: number;
  };
  contributors?: Array<{
    name?: string;
    website?: string;
    _type: "contributor";
    _key: string;
  }>;
  roles?: Array<string>;
  links?: Array<{
    title?: string;
    url?: string;
    _type: "link";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  content?: Array<{
    children?: Array<
      | {
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }
      | {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }
      | {
          asset?: SanityFileAssetReference;
          media?: unknown;
          _type: "video";
          _key: string;
        }
    >;
    style?: "normal" | "h3" | "h4" | "h5" | "h6";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  further_discovery?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Module
  | Slug
  | SanityImageAssetReference
  | SanityFileAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: ALL_PROJECTS
// Query: *[  _type == "project"  && defined(slug.current)]|order(time.year desc)[0...12]{    _id,    short_title,    slug,    location,    time,    type,    category,    partner,    thumbnail{      ...,      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height    }  }
export type ALL_PROJECTS_RESULT = Array<{
  _id: string;
  short_title: string | null;
  slug: Slug | null;
  location: {
    name?: string;
    website?: string;
  } | null;
  time: {
    duration?: string;
    year?: number;
  } | null;
  type: "client" | "internship" | "other" | "personal" | "studio" | null;
  category:
    | "ai-tool"
    | "app"
    | "digital-tool"
    | "graphic-design"
    | "system-interface"
    | "web-application"
    | "website"
    | null;
  partner: {
    label?: string;
    value?: string;
    link?: string;
  } | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    width: number | null;
    height: number | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: RECENT_PROJECTS
// Query: *[  _type == "project"  && defined(slug.current)]|order(time.year desc)[0...3]{    _id,    short_title,    slug,    location,    time,    type,    category,    partner,    thumbnail{      ...,      "width": asset->metadata.dimensions.width,      "height": asset->metadata.dimensions.height    }  }
export type RECENT_PROJECTS_RESULT = Array<{
  _id: string;
  short_title: string | null;
  slug: Slug | null;
  location: {
    name?: string;
    website?: string;
  } | null;
  time: {
    duration?: string;
    year?: number;
  } | null;
  type: "client" | "internship" | "other" | "personal" | "studio" | null;
  category:
    | "ai-tool"
    | "app"
    | "digital-tool"
    | "graphic-design"
    | "system-interface"
    | "web-application"
    | "website"
    | null;
  partner: {
    label?: string;
    value?: string;
    link?: string;
  } | null;
  thumbnail: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    width: number | null;
    height: number | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[\n  _type == "project"\n  && defined(slug.current)]|order(time.year desc)[0...12]{\n    _id,\n    short_title,\n    slug,\n    location,\n    time,\n    type,\n    category,\n    partner,\n    thumbnail{\n      ...,\n      "width": asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height\n    }\n  }': ALL_PROJECTS_RESULT;
    '*[\n  _type == "project"\n  && defined(slug.current)]|order(time.year desc)[0...3]{\n    _id,\n    short_title,\n    slug,\n    location,\n    time,\n    type,\n    category,\n    partner,\n    thumbnail{\n      ...,\n      "width": asset->metadata.dimensions.width,\n      "height": asset->metadata.dimensions.height\n    }\n  }\n': RECENT_PROJECTS_RESULT;
  }
}
